In [20]:
# import warnings
# warnings.simplefilter('ignore')

# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [21]:
# Read the csv file into a pandas DataFrame

exo = pd.read_csv('exo_clean.csv')
exo.head()

koi_disposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0       CONFIRMED      1.000              0              0              0   
1       CONFIRMED      0.969              0              0              0   
2  FALSE POSITIVE      0.000              0              1              0   
3  FALSE POSITIVE      0.000              0              1              0   
4       CONFIRMED      1.000              0              0              0   

   koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0              0    9.488036     2.775000e-05    -2.775000e-05   170.538750   
1              0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
2              0   19.899140     1.494000e-05    -1.494000e-05   175.850252   
3              0    1.736952     2.630000e-07    -2.630000e-07   170.307565   
4              0    2.525592     3.761000e-06    -3.761000e-06   171.595550   

   ...  koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  koi_srad  \
0  ...           -81.0      4.467           0.064          -0.096     0.927   
1  ...           -81.0      4.467           0.064          -0.096     0.927   
2  ...          -176.0      4.544           0.044          -0.176     0.868   
3  ...          -174.0      4.564           0.053          -0.168     0.791   
4  ...          -211.0      4.438           0.070          -0.210     1.046   

   koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag  
0          0.105         -0.061  291.93423  48.141651      15.347  
1          0.105         -0.061  291.93423  48.141651      15.347  
2          0.233         -0.078  297.00482  48.134129      15.436  
3          0.201         -0.067  285.53461  48.285210      15.597  
4          0.334         -0.133  288.75488  48.226200      15.509  

[5 rows x 42 columns]

In [22]:
exo.columns


Index(['koi_disposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_insol', 'koi_insol_err1',
       'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff',
       'koi_steff_err1', 'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1',
       'koi_slogg_err2', 'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra',
       'dec', 'koi_kepmag'],
      dtype='object')

In [24]:
target = exo['koi_disposition']
data = exo.drop(['koi_disposition'], axis=1)
feature_names = data.columns
data.head()

koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0      1.000              0              0              0              0   
1      0.969              0              0              0              0   
2      0.000              0              1              0              0   
3      0.000              0              1              0              0   
4      1.000              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0    9.488036     2.775000e-05    -2.775000e-05   170.538750   
1   54.418383     2.479000e-04    -2.479000e-04   162.513840   
2   19.899140     1.494000e-05    -1.494000e-05   175.850252   
3    1.736952     2.630000e-07    -2.630000e-07   170.307565   
4    2.525592     3.761000e-06    -3.761000e-06   171.595550   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.002160  ...           -81.0      4.467           0.064   
1          0.003520  ...           -81.0      4.467           0.064   
2          0.000581  ...          -176.0      4.544           0.044   
3          0.000115  ...          -174.0      4.564           0.053   
4          0.001130  ...          -211.0      4.438           0.070   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.096     0.927          0.105         -0.061  291.93423   
2          -0.176     0.868          0.233         -0.078  297.00482   
3          -0.168     0.791          0.201         -0.067  285.53461   
4          -0.210     1.046          0.334         -0.133  288.75488   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.141651      15.347  
2  48.134129      15.436  
3  48.285210      15.597  
4  48.226200      15.509  

[5 rows x 41 columns]

In [25]:
# create train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [26]:
X_train.head()

koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
6160      0.994              0              0              0              0   
2164      0.717              0              0              0              0   
4626      0.999              0              0              0              0   
6074      0.000              1              0              0              0   
4663      0.905              0              0              0              0   

      koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
6160    8.609654         0.000070        -0.000070    134.38829   
2164   88.071277         0.000850        -0.000850    214.51304   
4626    5.709408         0.000018        -0.000018    137.12208   
6074  659.290700         0.011970        -0.011970    254.33000   
4663    6.685438         0.000183        -0.000183    132.31840   

      koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
6160           0.00653  ...          -171.0      3.447           0.884   
2164           0.00740  ...           -79.0      4.506           0.072   
4626           0.00256  ...          -144.0      4.682           0.045   
6074           0.01710  ...           -83.0      4.050           0.018   
4663           0.01420  ...           -78.0      4.326           0.110   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
6160          -0.156     4.233          0.785         -3.139  291.02719   
2164          -0.022     0.819          0.032         -0.055  292.30743   
4626          -0.036     0.572          0.049         -0.049  285.60254   
6074          -0.018     1.837          0.124         -0.124  294.37708   
4663          -0.110     1.159          0.185         -0.151  295.55374   

            dec  koi_kepmag  
6160  37.613911      12.765  
2164  46.626640      15.639  
4626  50.112041      14.265  
6074  47.289928      10.629  
4663  46.029110      15.135  

[5 rows x 41 columns]

In [27]:
y_train.head()

6160         CANDIDATE
2164         CANDIDATE
4626         CONFIRMED
6074    FALSE POSITIVE
4663         CANDIDATE
Name: koi_disposition, dtype: object

In [28]:
# Pre processing
from sklearn.preprocessing import MinMaxScaler
X_minmax = MinMaxScaler().fit(X_train)
X_train_minmax = X_minmax.transform(X_train)
X_test_minmax = X_minmax.transform(X_test)

In [32]:
print(X_minmax)
print(X_train_minmax)
print(X_test_minmax)

MinMaxScaler()
[[0.994      0.         0.         ... 0.51092035 0.06577539 0.5249389 ]
 [0.717      0.         0.         ... 0.56947323 0.63769881 0.78510003]
 [0.999      0.         0.         ... 0.2628193  0.85887294 0.66072237]
 ...
 [1.         0.         0.         ... 0.3723727  0.91168762 0.58794243]
 [0.912      0.         0.         ... 0.81595249 0.61472975 0.72589843]
 [0.05       1.         0.         ... 0.59970098 0.27774358 0.74364081]]
[[0.999      0.         0.         ... 0.66362782 0.84637293 0.81153254]
 [0.997      0.         0.         ... 0.40754724 0.62296282 0.78872092]
 [0.         0.         0.         ... 0.36489169 0.16733163 0.61473703]
 ...
 [0.146      1.         0.         ... 0.68831833 0.43179568 0.81117045]
 [0.943      0.         0.         ... 0.29930692 0.75797076 0.7740563 ]
 [0.         0.         0.         ... 0.56064804 0.70768092 0.78238436]]


### Train the model (SVM)

In [37]:
from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(X_train_minmax, y_train)

SVC(kernel='linear')

In [38]:
print(f"Training Data Score: {model.score(X_train_minmax, y_train)}")
print(f"Testing Data Score: {model.score(X_test_minmax, y_test)}")

Training Data Score: 0.8385167464114832
Testing Data Score: 0.8339313172731933


### Hyperparameter tuning

In [40]:
# gridsearchcv
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1,5,10,50],
              'gamma': [0.0001,0.0005,0.001,0.005]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [43]:
grid.fit(X_train_minmax, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 1/5] END .................C=1, gamma=0.0001;, score=0.829 total time=   0.4s
[CV 2/5] END .................C=1, gamma=0.0001;, score=0.848 total time=   0.4s
[CV 3/5] END .................C=1, gamma=0.0001;, score=0.838 total time=   0.4s
[CV 4/5] END .................C=1, gamma=0.0001;, score=0.837 total time=   0.3s
[CV 5/5] END .................C=1, gamma=0.0001;, score=0.832 total time=   0.3s
[CV 1/5] END .................C=1, gamma=0.0005;, score=0.829 total time=   0.4s
[CV 2/5] END .................C=1, gamma=0.0005;, score=0.848 total time=   0.3s
[CV 3/5] END .................C=1, gamma=0.0005;, score=0.838 total time=   0.4s
[CV 4/5] END .................C=1, gamma=0.0005;, score=0.837 total time=   0.3s
[CV 5/5] END .................C=1, gamma=0.0005;, score=0.832 total time=   0.4s
[CV 1/5] END ..................C=1, gamma=0.001;, score=0.829 total time=   0.3s
[CV 2/5] END ..................C=1, gamma=0.001;

GridSearchCV(estimator=SVC(kernel='linear'),
             param_grid={'C': [1, 5, 10, 50],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005]},
             verbose=3)

In [44]:
# print best params and score
print(grid.best_params_)
print(grid.best_score_)

{'C': 50, 'gamma': 0.0001}
0.8720085835030327


In [45]:
# print training score
grid.score(X_train_minmax, y_train)

0.8764524948735475

In [46]:
# print testing score
grid.score(X_test_minmax,y_test)

0.8815991799077396

In [48]:
# make predictions
predictions = grid.predict(X_test_minmax)
print(predictions)

['CONFIRMED' 'CONFIRMED' 'FALSE POSITIVE' ... 'FALSE POSITIVE' 'CANDIDATE'
 'FALSE POSITIVE']


In [50]:
# print classification
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

                precision    recall  f1-score   support

     CANDIDATE       0.86      0.61      0.71       446
     CONFIRMED       0.75      0.90      0.82       572
FALSE POSITIVE       0.99      1.00      0.99       933

      accuracy                           0.88      1951
     macro avg       0.86      0.84      0.84      1951
  weighted avg       0.89      0.88      0.88      1951



In [ ]:
# save the model
import joblib
filename = 